version: '3'

services:
  apache:
    build: ./php-apache-mysqli
    image: php-apache-mysqli
    container_name: php-apache-mysqli
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mysqlserver
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=myPassword
      - MYSQL_DATABASE=myDataBase

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db